os: linux
dist: bionic
language: cpp
compiler: clang

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm

env:
  - LLVM_VERSION="10-init" CXX="clang++-10" CC="clang-10"
  - LLVM_VERSION=9.0.0 CXX="clang++-10" CC="clang-10"
  - LLVM_VERSION=8.0.1 CXX="clang++-10" CC="clang-10"
  - LLVM_VERSION=7.1.0 CXX="clang++-10" CC="clang-10"

script:
  - git clone --branch llvmorg-${LLVM_VERSION} --depth 1 https://github.com/llvm/llvm-project.git
  - cd llvm-project && mkdir build && cd build
  - cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_STATIC=true -G "Unix Makefiles" ../llvm
  - make clang-format -j4

deploy:
  provider: releases
  api_key:
    secure: GhnIUnEVbcNPyGMB5OzB/esKZtVZtOfQTzPmA/ZBUWTw7z7C3742u+eoTgPQ/lGY4S5AGBal62cROoxt2pNxfmHRFmTOdiHbZqA1GFxV0+q4iwNUhdwyMtsqqsbMJON/mzl6TyNI8OyTSmyxncEdnXRo2I6T3UC/fDRZr+8DINRl7BL19neVS9nz6+Zs8F7JtMpY7Adcjb9XF8L55CSXhKIzGZ+dVgIsRlHDyYXakF6MnY0qgRCG1YZyJnq7e0XB6W1Z+ZkqohdAHhHM+yoW2woIxvcLEcC1quya5G+Woldr+b4zLGvrtTo7Scnu48rjZP4YMEHFzevuqWrNg7Uokl/bSdHP8/OnLPzuZrKHmXw/BI1BZuvlNIKlr1Bakpngq8c3nFkW+3fwpVfjcd5AJvBSJPa7t6aIRw4Y3ZqaoJpOyx0QUQ7wIIkbjL0bE/HMfzdUXSDxjdvoEEuXMSAdG9V/TAFRzeNDRsWAm5tnXWxMD4YIb0iYkjOfxk3+q8lQNRLLogDJoBu6NGal/b75JAOMde6v4YZj2qf++Ui3ZXQR3hCNofxj9Tx5puKk8nXmPEcyK9tQsv8bHDP/hD9v98Fr7euQMDIleuWHumyU6ZyP5md9Zwtam1T1fFJoQ5WraFTiP4uaql+KgTFO1YpLdv0CLQNHpsyJTAYkC874fLA=
  file: ${TRAVIS_BUILD_DIR}/llvm-project/build/bin/clang-format
  on:
    repo: janmayer/clang-tools-anywhere
  skip_cleanup: true
  overwrite: true
